//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsManager.Infrastructure.Resources.Services {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactsService_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactsService_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ContactsManager.Infrastructure.Resources.Services.ContactsService_ar", typeof(ContactsService_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CSVContactNotFound {
            get {
                return ResourceManager.GetString("CSVContactNotFound", resourceCulture);
            }
        }
        
        internal static string CSVHeaderDoesNotMatch {
            get {
                return ResourceManager.GetString("CSVHeaderDoesNotMatch", resourceCulture);
            }
        }
        
        internal static string CSVInvalidFormat {
            get {
                return ResourceManager.GetString("CSVInvalidFormat", resourceCulture);
            }
        }
        
        internal static string CSVErrors {
            get {
                return ResourceManager.GetString("CSVErrors", resourceCulture);
            }
        }
        
        internal static string CSVSuccess {
            get {
                return ResourceManager.GetString("CSVSuccess", resourceCulture);
            }
        }
        
        internal static string JSONContactNotFound {
            get {
                return ResourceManager.GetString("JSONContactNotFound", resourceCulture);
            }
        }
        
        internal static string JSONInvalidFormat {
            get {
                return ResourceManager.GetString("JSONInvalidFormat", resourceCulture);
            }
        }
        
        internal static string JSONErrors {
            get {
                return ResourceManager.GetString("JSONErrors", resourceCulture);
            }
        }
        
        internal static string JSONSuccess {
            get {
                return ResourceManager.GetString("JSONSuccess", resourceCulture);
            }
        }
    }
}
