//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsManager.Infrastructure.Resources.Services.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountService_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountService_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ContactsManager.Infrastructure.Resources.Services.Account.AccountService_ar", typeof(AccountService_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("EmailOrPasswordInvalid", resourceCulture);
            }
        }
        
        internal static string FailedToDeleteAccount {
            get {
                return ResourceManager.GetString("FailedToDeleteAccount", resourceCulture);
            }
        }
        
        internal static string FailedToChangeUserName {
            get {
                return ResourceManager.GetString("FailedToChangeUserName", resourceCulture);
            }
        }
        
        internal static string FailedToChangeEmail {
            get {
                return ResourceManager.GetString("FailedToChangeEmail", resourceCulture);
            }
        }
        
        internal static string FailedToChangePhoneNumber {
            get {
                return ResourceManager.GetString("FailedToChangePhoneNumber", resourceCulture);
            }
        }
        
        internal static string FailedToChangePassword {
            get {
                return ResourceManager.GetString("FailedToChangePassword", resourceCulture);
            }
        }
        
        internal static string FailedToConfirmPassword {
            get {
                return ResourceManager.GetString("FailedToConfirmPassword", resourceCulture);
            }
        }
        
        internal static string FailedToResetPassword {
            get {
                return ResourceManager.GetString("FailedToResetPassword", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string FailedToChangeUserPreferences {
            get {
                return ResourceManager.GetString("FailedToChangeUserPreferences", resourceCulture);
            }
        }
    }
}
