//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsManager.Presentation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ContactsManager.Presentation.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConfirmEmailChange {
            get {
                return ResourceManager.GetString("ConfirmEmailChange", resourceCulture);
            }
        }
        
        internal static string EnterPasswordToChangeEmail {
            get {
                return ResourceManager.GetString("EnterPasswordToChangeEmail", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string ConfirmPasswordChange {
            get {
                return ResourceManager.GetString("ConfirmPasswordChange", resourceCulture);
            }
        }
        
        internal static string EnterPasswordToChangePassword {
            get {
                return ResourceManager.GetString("EnterPasswordToChangePassword", resourceCulture);
            }
        }
        
        internal static string ConfirmAccountDeletion {
            get {
                return ResourceManager.GetString("ConfirmAccountDeletion", resourceCulture);
            }
        }
        
        internal static string ConfirmAccountDeletionMessage {
            get {
                return ResourceManager.GetString("ConfirmAccountDeletionMessage", resourceCulture);
            }
        }
        
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
    }
}
